apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: trivago
spec:
  host: trivago
  subsets:
  - name: java
    labels:
      version: java
  - name: go
    labels:
      version: go