apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-java
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: wr-java
 minReplicas: 1
 maxReplicas: 2
 targetCPUUtilizationPercentage: 80
