apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-go
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: trivago-go
 minReplicas: 1
 maxReplicas: 2
 targetCPUUtilizationPercentage: 80